export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const INCREMENT = 'INCTEMENT'

export const SELECT_ARTICLES = 'SELECT_ARTICLES'

export const CHANGE_DATE_FROM = 'CHANGE_DATE_FROM'

export const CHANGE_DATE_TO = 'CHANGE_DATE_TO'

export const ADD_COMMENT = 'ADD_COMMENT'

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const START = '_START'

export const SUCCESS = '_SUCCESS'

export const FAIL = '_FAIL'

export const LOAD_ARTICLE = 'LOAD_ARTICLE'

export const LOAD_ARTICLE_COMMENTS = 'LOAD_ARTICLE_COMMENTS'

export const LOAD_ALL_COMMENTS = 'LOAD_ALL_COMMENTS'

export const LOAD_COMMENTS_PAGE = 'LOAD_COMMENTS_PAGE'